/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as PublierRouteImport } from './routes/publier'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as VerifierEmailRouteImport } from './routes/verifier-email'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCompteRouteImport } from './routes/_authenticated/compte'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMonBesoinRouteImport } from './routes/_authenticated/mon-besoin'
import { Route as ProfesseursIndexRouteImport } from './routes/professeurs.index'
import { Route as ProfesseursIdRouteImport } from './routes/professeurs.$id'
import { Route as AuthenticatedDemandesIndexRouteImport } from './routes/_authenticated/demandes.index'
import { Route as AuthenticatedDemandesIdRouteImport } from './routes/_authenticated/demandes.$id'
import { Route as AuthenticatedProIndexRouteImport } from './routes/_authenticated/pro.index'
import { Route as AuthenticatedProDemandesRouteImport } from './routes/_authenticated/pro.demandes'
import { Route as AuthenticatedProInscriptionRouteImport } from './routes/_authenticated/pro.inscription'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const PublierRoute = PublierRouteImport.update({
  id: '/publier',
  path: '/publier',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifierEmailRoute = VerifierEmailRouteImport.update({
  id: '/verifier-email',
  path: '/verifier-email',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompteRoute = AuthenticatedCompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonBesoinRoute = AuthenticatedMonBesoinRouteImport.update({
  id: '/mon-besoin',
  path: '/mon-besoin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ProfesseursIndexRoute = ProfesseursIndexRouteImport.update({
  id: '/professeurs/',
  path: '/professeurs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesseursIdRoute = ProfesseursIdRouteImport.update({
  id: '/professeurs/$id',
  path: '/professeurs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDemandesIndexRoute =
  AuthenticatedDemandesIndexRouteImport.update({
    id: '/demandes/',
    path: '/demandes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemandesIdRoute = AuthenticatedDemandesIdRouteImport.update({
  id: '/demandes/$id',
  path: '/demandes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProIndexRoute = AuthenticatedProIndexRouteImport.update({
  id: '/pro/',
  path: '/pro/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProDemandesRoute =
  AuthenticatedProDemandesRouteImport.update({
    id: '/pro/demandes',
    path: '/pro/demandes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProInscriptionRoute =
  AuthenticatedProInscriptionRouteImport.update({
    id: '/pro/inscription',
    path: '/pro/inscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/inscription': typeof InscriptionRoute
  '/publier': typeof PublierRoute
  '/tarifs': typeof TarifsRoute
  '/verifier-email': typeof VerifierEmailRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/compte': typeof AuthenticatedCompteRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/mon-besoin': typeof AuthenticatedMonBesoinRoute
  '/professeurs/$id': typeof ProfesseursIdRoute
  '/professeurs/': typeof ProfesseursIndexRoute
  '/demandes/$id': typeof AuthenticatedDemandesIdRoute
  '/pro/demandes': typeof AuthenticatedProDemandesRoute
  '/pro/inscription': typeof AuthenticatedProInscriptionRoute
  '/demandes/': typeof AuthenticatedDemandesIndexRoute
  '/pro/': typeof AuthenticatedProIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/inscription': typeof InscriptionRoute
  '/publier': typeof PublierRoute
  '/tarifs': typeof TarifsRoute
  '/verifier-email': typeof VerifierEmailRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/compte': typeof AuthenticatedCompteRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/mon-besoin': typeof AuthenticatedMonBesoinRoute
  '/professeurs/$id': typeof ProfesseursIdRoute
  '/professeurs': typeof ProfesseursIndexRoute
  '/demandes/$id': typeof AuthenticatedDemandesIdRoute
  '/pro/demandes': typeof AuthenticatedProDemandesRoute
  '/pro/inscription': typeof AuthenticatedProInscriptionRoute
  '/demandes': typeof AuthenticatedDemandesIndexRoute
  '/pro': typeof AuthenticatedProIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/inscription': typeof InscriptionRoute
  '/publier': typeof PublierRoute
  '/tarifs': typeof TarifsRoute
  '/verifier-email': typeof VerifierEmailRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/compte': typeof AuthenticatedCompteRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/mon-besoin': typeof AuthenticatedMonBesoinRoute
  '/professeurs/$id': typeof ProfesseursIdRoute
  '/professeurs/': typeof ProfesseursIndexRoute
  '/_authenticated/demandes/$id': typeof AuthenticatedDemandesIdRoute
  '/_authenticated/pro/demandes': typeof AuthenticatedProDemandesRoute
  '/_authenticated/pro/inscription': typeof AuthenticatedProInscriptionRoute
  '/_authenticated/demandes/': typeof AuthenticatedDemandesIndexRoute
  '/_authenticated/pro/': typeof AuthenticatedProIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/inscription'
    | '/publier'
    | '/tarifs'
    | '/verifier-email'
    | '/verify-email'
    | '/admin'
    | '/compte'
    | '/messages'
    | '/mon-besoin'
    | '/professeurs/$id'
    | '/professeurs/'
    | '/demandes/$id'
    | '/pro/demandes'
    | '/pro/inscription'
    | '/demandes/'
    | '/pro/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/inscription'
    | '/publier'
    | '/tarifs'
    | '/verifier-email'
    | '/verify-email'
    | '/admin'
    | '/compte'
    | '/messages'
    | '/mon-besoin'
    | '/professeurs/$id'
    | '/professeurs'
    | '/demandes/$id'
    | '/pro/demandes'
    | '/pro/inscription'
    | '/demandes'
    | '/pro'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/inscription'
    | '/publier'
    | '/tarifs'
    | '/verifier-email'
    | '/verify-email'
    | '/_authenticated/admin'
    | '/_authenticated/compte'
    | '/_authenticated/messages'
    | '/_authenticated/mon-besoin'
    | '/professeurs/$id'
    | '/professeurs/'
    | '/_authenticated/demandes/$id'
    | '/_authenticated/pro/demandes'
    | '/_authenticated/pro/inscription'
    | '/_authenticated/demandes/'
    | '/_authenticated/pro/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  InscriptionRoute: typeof InscriptionRoute
  PublierRoute: typeof PublierRoute
  TarifsRoute: typeof TarifsRoute
  VerifierEmailRoute: typeof VerifierEmailRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ProfesseursIdRoute: typeof ProfesseursIdRoute
  ProfesseursIndexRoute: typeof ProfesseursIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publier': {
      id: '/publier'
      path: '/publier'
      fullPath: '/publier'
      preLoaderRoute: typeof PublierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifier-email': {
      id: '/verifier-email'
      path: '/verifier-email'
      fullPath: '/verifier-email'
      preLoaderRoute: typeof VerifierEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compte': {
      id: '/_authenticated/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof AuthenticatedCompteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon-besoin': {
      id: '/_authenticated/mon-besoin'
      path: '/mon-besoin'
      fullPath: '/mon-besoin'
      preLoaderRoute: typeof AuthenticatedMonBesoinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/professeurs/': {
      id: '/professeurs/'
      path: '/professeurs'
      fullPath: '/professeurs/'
      preLoaderRoute: typeof ProfesseursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professeurs/$id': {
      id: '/professeurs/$id'
      path: '/professeurs/$id'
      fullPath: '/professeurs/$id'
      preLoaderRoute: typeof ProfesseursIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/demandes/': {
      id: '/_authenticated/demandes/'
      path: '/demandes'
      fullPath: '/demandes/'
      preLoaderRoute: typeof AuthenticatedDemandesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demandes/$id': {
      id: '/_authenticated/demandes/$id'
      path: '/demandes/$id'
      fullPath: '/demandes/$id'
      preLoaderRoute: typeof AuthenticatedDemandesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro/': {
      id: '/_authenticated/pro/'
      path: '/pro'
      fullPath: '/pro/'
      preLoaderRoute: typeof AuthenticatedProIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro/demandes': {
      id: '/_authenticated/pro/demandes'
      path: '/pro/demandes'
      fullPath: '/pro/demandes'
      preLoaderRoute: typeof AuthenticatedProDemandesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro/inscription': {
      id: '/_authenticated/pro/inscription'
      path: '/pro/inscription'
      fullPath: '/pro/inscription'
      preLoaderRoute: typeof AuthenticatedProInscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCompteRoute: typeof AuthenticatedCompteRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedMonBesoinRoute: typeof AuthenticatedMonBesoinRoute
  AuthenticatedDemandesIdRoute: typeof AuthenticatedDemandesIdRoute
  AuthenticatedProDemandesRoute: typeof AuthenticatedProDemandesRoute
  AuthenticatedProInscriptionRoute: typeof AuthenticatedProInscriptionRoute
  AuthenticatedDemandesIndexRoute: typeof AuthenticatedDemandesIndexRoute
  AuthenticatedProIndexRoute: typeof AuthenticatedProIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCompteRoute: AuthenticatedCompteRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedMonBesoinRoute: AuthenticatedMonBesoinRoute,
  AuthenticatedDemandesIdRoute: AuthenticatedDemandesIdRoute,
  AuthenticatedProDemandesRoute: AuthenticatedProDemandesRoute,
  AuthenticatedProInscriptionRoute: AuthenticatedProInscriptionRoute,
  AuthenticatedDemandesIndexRoute: AuthenticatedDemandesIndexRoute,
  AuthenticatedProIndexRoute: AuthenticatedProIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  InscriptionRoute: InscriptionRoute,
  PublierRoute: PublierRoute,
  TarifsRoute: TarifsRoute,
  VerifierEmailRoute: VerifierEmailRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ProfesseursIdRoute: ProfesseursIdRoute,
  ProfesseursIndexRoute: ProfesseursIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
